//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTEColones
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioMaterialEstudiante
    {
        public int IdCambioMaterialEstudiante { get; set; }
        public int IdHistorialTipoMaterial { get; set; }
        public int IdEstudiante { get; set; }
        public int IdEncargadoCentroAcopio { get; set; }
        public Nullable<int> IdHistorialPromocion { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public double PesoReciclaje { get; set; }
        public double TecolonesAdquiridos { get; set; }
    
        public virtual EncargadoCentroAcopio EncargadoCentroAcopio { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual HistorialPromocion HistorialPromocion { get; set; }
        public virtual HistorialTipoMaterial HistorialTipoMaterial { get; set; }
    }
}
