//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTEColones
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoBeneficio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoBeneficio()
        {
            this.HistorialTipoBeneficios = new HashSet<HistorialTipoBeneficio>();
        }
    
        public int IdTipoBeneficio { get; set; }
        public string NombreBeneficio { get; set; }
        public string DescripcionBeneficio { get; set; }
        public bool EstadoBeneficio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialTipoBeneficio> HistorialTipoBeneficios { get; set; }
    }
}
